version: 'latest'

services:
  postgres:
    image: postgres:latest
    env_file: ./.env
    container_name: postgres_auth
    ports:
      - '5432:5432'
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
